language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - 7.0

## Run on container environment
sudo: false

## Cache composer bits
cache:
  directories:
    - bin
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - ./bin/phpspec run --format=pretty
  - ./bin/phpunit --testdox
